services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd portfolio_project && gunicorn portfolio_project.wsgi:application"
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.7"
